#!/usr/bin/env python3
"""Dump the FastAPI route surface to docs/api-surface.txt.

Phase 0 records the public HTTP/WebSocket surface so later phases can diff
against it and prove they only added routes (plus any documented removals).

Usage:
    python scripts/dump_api.py            # print to stdout
    python scripts/dump_api.py --write    # write docs/api-surface.txt
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Import-time env the app expects; harmless in this offline, no-network dump.
os.environ.setdefault("SUPABASE_URL", "https://dump.local")
os.environ.setdefault("SUPABASE_SERVICE_KEY", "dump-key")

# Ensure `app` is importable when run from repo root or backend/.
_BACKEND = Path(__file__).resolve().parent.parent
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))


def _websocket_routes(routes: object, out: list[str]) -> None:
    """Recursively collect WebSocket routes (FastAPI 0.138 nests included routers)."""
    from fastapi.routing import APIWebSocketRoute

    for route in routes or []:  # type: ignore[union-attr]
        if isinstance(route, APIWebSocketRoute):
            out.append(f"{'WEBSOCKET':<12} {route.path}")
        nested = getattr(route, "original_router", None)
        if nested is not None:
            _websocket_routes(getattr(nested, "routes", []), out)


def collect_routes() -> list[str]:
    from app.main import app

    lines: list[str] = []
    # HTTP routes from the OpenAPI schema — stable across FastAPI's internal
    # routing changes (0.138 includes routers lazily, so app.routes no longer
    # flattens them).
    for path, methods in app.openapi().get("paths", {}).items():
        verbs = sorted(m.upper() for m in methods if m.upper() != "HEAD")
        if verbs:
            lines.append(f"{','.join(verbs):<12} {path}")
    _websocket_routes(app.routes, lines)
    return sorted(set(lines))


def render() -> str:
    routes = collect_routes()
    header = [
        "# Forge public API surface",
        "# Generated by scripts/dump_api.py — diff later phases against this file.",
        f"# Route count: {len(routes)}",
        "",
    ]
    return "\n".join(header + routes) + "\n"


def main() -> None:
    text = render()
    if "--write" in sys.argv:
        out = _BACKEND.parent / "docs" / "api-surface.txt"
        out.parent.mkdir(exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print(f"Wrote {out} ({text.count(chr(10))} lines)")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
