#!/usr/bin/env python3
"""Dump the FastAPI route surface to docs/api-surface.txt.

Phase 0 records the public HTTP/WebSocket surface so later phases can diff
against it and prove they only added routes (plus any documented removals).

Usage:
    python scripts/dump_api.py            # print to stdout
    python scripts/dump_api.py --write    # write docs/api-surface.txt
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

# Import-time env the app expects; harmless in this offline, no-network dump.
os.environ.setdefault("SUPABASE_URL", "https://dump.local")
os.environ.setdefault("SUPABASE_SERVICE_KEY", "dump-key")

# Ensure `app` is importable when run from repo root or backend/.
_BACKEND = Path(__file__).resolve().parent.parent
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))


def collect_routes() -> list[str]:
    from fastapi.routing import APIRoute, APIWebSocketRoute

    from app.main import app

    lines: list[str] = []
    for route in app.routes:
        if isinstance(route, APIRoute):
            methods = ",".join(sorted(m for m in route.methods if m != "HEAD"))
            lines.append(f"{methods:<12} {route.path}")
        elif isinstance(route, APIWebSocketRoute):
            lines.append(f"{'WEBSOCKET':<12} {route.path}")
    return sorted(set(lines))


def render() -> str:
    routes = collect_routes()
    header = [
        "# Forge public API surface",
        "# Generated by scripts/dump_api.py — diff later phases against this file.",
        f"# Route count: {len(routes)}",
        "",
    ]
    return "\n".join(header + routes) + "\n"


def main() -> None:
    text = render()
    if "--write" in sys.argv:
        out = _BACKEND.parent / "docs" / "api-surface.txt"
        out.parent.mkdir(exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print(f"Wrote {out} ({text.count(chr(10))} lines)")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
