import Link from "next/link";
import { Button } from "@/components/ui/button";

const sections = [
  {
    title: "Getting Started",
    items: [
      {
        heading: "1. Create an account",
        text: "Sign up at the login page with your email and password. You'll be redirected to the dashboard automatically.",
      },
      {
        heading: "2. Create your first agent",
        text: 'Navigate to Agents in the sidebar, click "New Agent", give it a name, system prompt, and select tools. Or pick from a pre-built template.',
      },
      {
        heading: "3. Run the agent",
        text: "Open your agent and type an input. The agent streams its response in real-time via SSE. View run history and token usage on the Runs page.",
      },
      {
        heading: "4. Install the CLI",
        text: 'pip install forge-cli, then run "forge init" to configure your API URL and key. Use "forge status" for a quick overview.',
      },
    ],
  },
  {
    title: "Creating Agents",
    items: [
      {
        heading: "Agent fields",
        text: "Each agent has a name, system prompt, tools array, workflow steps, and an optional model override. Leave the model blank to use the default.",
      },
      {
        heading: "Templates",
        text: "Four built-in templates: Document Analyzer, Research Agent, Data Extractor, and Code Reviewer. Create an agent from a template to inherit its configuration.",
      },
      {
        heading: "Multi-agent orchestration",
        text: "Submit an objective to the orchestration endpoint. The system decomposes it into sub-tasks, assigns agents, tracks dependencies, and aggregates results.",
      },
    ],
  },
  {
    title: "Blueprints",
    items: [
      {
        heading: "Visual workflow editor",
        text: "Blueprints are DAGs of nodes. Each node is a processing step — LLM calls, text splitting, JSON validation, template rendering, or knowledge retrieval.",
      },
      {
        heading: "Node types",
        text: "15 node types: 10 deterministic (text_splitter, template_renderer, json_validator, output_formatter, knowledge_retrieval, etc.) and 5 agent-backed (llm_call, summarizer, classifier, router, approval_gate).",
      },
      {
        heading: "Execution",
        text: "The blueprint engine topologically sorts nodes, respects dependencies, and executes independent nodes concurrently. Context assembly manages token budgets across nodes.",
      },
    ],
  },
  {
    title: "CLI Usage",
    items: [
      {
        heading: "Core commands",
        text: "forge status — active runs overview. forge dashboard — live TUI. forge costs — token usage and spend. forge agents list/create — manage agents.",
      },
      {
        heading: "Feature commands",
        text: "forge blueprints, evals, triggers, approvals, traces, prompts, knowledge, marketplace, teams, mail — each manages its respective feature.",
      },
      {
        heading: "Configuration",
        text: 'Run "forge init" to create ~/.forge/config.toml. Set api_url (your backend URL) and api_key (your API key starting with af_).',
      },
    ],
  },
  {
    title: "API Reference",
    items: [
      {
        heading: "OpenAPI spec",
        text: "The full API spec is auto-generated by FastAPI and available at /docs on the backend. It includes all endpoints, request/response schemas, and authentication details.",
      },
      {
        heading: "Authentication",
        text: "All API endpoints require a Bearer token — either a Supabase JWT from login or an API key (af_ prefix) generated via POST /api/keys.",
      },
      {
        heading: "Key endpoints",
        text: "POST /api/agents (create), GET /api/agents (list), POST /api/agents/:id/run (execute with SSE), GET /api/dashboard/metrics, GET /costs/summary, POST /api/blueprints, GET /marketplace/listings.",
      },
    ],
  },
];

export default function DocsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <header className="border-b border-border">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-6">
          <div className="flex items-center gap-2">
            <Link href="/" className="flex items-center gap-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground font-bold text-sm">
                AF
              </div>
              <span className="text-xl font-bold">Forge</span>
            </Link>
            <span className="text-muted-foreground ml-2">/ Docs</span>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/dashboard">
              <Button variant="ghost">Dashboard</Button>
            </Link>
            <Link href="/login">
              <Button>Log in</Button>
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-4xl w-full px-6 py-12">
        <h1 className="text-4xl font-bold mb-2">Documentation</h1>
        <p className="text-muted-foreground mb-10">
          Everything you need to build, deploy, and monitor AI agent workflows
          with Forge.
        </p>

        <div className="space-y-12">
          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-2xl font-bold mb-4 border-b border-border pb-2">
                {section.title}
              </h2>
              <div className="space-y-4">
                {section.items.map((item) => (
                  <div key={item.heading}>
                    <h3 className="font-semibold">{item.heading}</h3>
                    <p className="text-sm text-muted-foreground mt-1">
                      {item.text}
                    </p>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-12 rounded-xl border border-border bg-card p-6">
          <h2 className="text-lg font-semibold mb-2">
            Interactive API Reference
          </h2>
          <p className="text-sm text-muted-foreground mb-4">
            The full OpenAPI specification is auto-generated and always
            up-to-date. It includes all endpoints, schemas, and authentication
            details.
          </p>
          <Button variant="outline" asChild>
            <a
              href={`${process.env.NEXT_PUBLIC_API_URL || ""}/docs`}
              target="_blank"
              rel="noopener noreferrer"
            >
              Open API Reference
            </a>
          </Button>
        </div>
      </main>

      <footer className="border-t border-border py-8 text-center text-sm text-muted-foreground">
        Forge — Open source AI agent platform
      </footer>
    </div>
  );
}
